**=========================================================================  
BIBLIOTECA: DETERMINAÇÃO DOS GRAUS DE LIBERDADE DOS ELEMENTOS
=========================================================================**  

In [3]:
def graus_de_lib_totais(nNos, nGrauPorNo):
    gdlTotal = []
    nGdlTotal = nNos*nGrauPorNo
    for grau in range(nGdlTotal): 
        gdlTotal.append(grau)
    return nGdlTotal, gdlTotal
    
def graus_de_lib_restritos(nApo, Apoios):
    gdlRestrito = []
    for apo in range(nApo):
        noAnalisado = Apoios[apo][0]
        restricaoX = Apoios[apo][1]
        if restricaoX == 1:
            gdlRestrito.append(2*noAnalisado)
        restricaoY = Apoios[apo][2]
        if restricaoY == 1:
            gdlRestrito.append(2*noAnalisado + 1)
    nGdlRestrito = len(gdlRestrito)
    return nGdlRestrito, gdlRestrito
    
def graus_de_lib_livres(gdlTotal, gdlRestrito):
    gdlLivre = np.setdiff1d(gdlTotal, gdlRestrito)
    nGdlLivre = len(gdlLivre)
    return nGdlLivre, gdlLivre

def forca_nodal(nGdlTotal, NumForNodal, ForExtNo):
    forcaNodal = np.zeros(shape=(nGdlTotal,1))
    for forca in range(NumForNodal):
        print(forca)
        noAnalisado = ForExtNo[forca][0]
        forcaX = ForExtNo[forca][1]
        forcaY = ForExtNo[forca][2]
        forcaNodal[2*noAnalisado][0] = forcaX
        forcaNodal[2*noAnalisado + 1][0] = forcaY
    return forcaNodal




In [2]:
import numpy as np
nNos = 10
nGrauPorNo = 2
TipoMalha = "CST0001"
TipoPresc = "Força"
NumIncrem = 10

nGdlTotal, gdlTotal = graus_de_lib_totais(nNos, nGrauPorNo)
print(nGdlTotal)
print(gdlTotal)

Apoios = np.array([[0, 1, 1],[9, 1, 1]]) 
NumApo, lixo = Apoios.shape

nGdlRestrito, gdlRestrito = graus_de_lib_restritos(NumApo, Apoios)
print(nGdlRestrito)
print(gdlRestrito)

nGdlLivre, gdlLivre = graus_de_lib_livres(gdlTotal, gdlRestrito)
print(nGdlLivre)
print(gdlLivre)

ForExtNo = np.array([[3, 5000, 0],[4, 5000, 0]])
NumForNodal, lixo = ForExtNo.shape
print(NumForNodal)
print(ForExtNo)

teste = forca_nodal(nGdlTotal, NumForNodal, ForExtNo)
print(teste)

20
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
4
[0, 1, 18, 19]
16
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
2
[[   3 5000    0]
 [   4 5000    0]]
0
1
[[   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [5000.]
 [   0.]
 [5000.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]
 [   0.]]
