In [1]:
from sympy import *
init_printing(pretty_print=True)
import numpy as np 

xi, eta, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, x, y, x1, x2, x3, y1, y2, y3= symbols('xi eta a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 x y x1 x2 x3 y1 y2 y3')

In [2]:
N1 = xi
N2 = eta
N3 = 1 - xi - eta
NN = np.array([N1, N2, N3])
print(NN)

[xi eta -eta - xi + 1]


In [3]:
Jacobiano1 = np.zeros((2,3))
for i in range(3):
        print(i)
        Jacobiano1[0][i] = diff(NN[i], xi)
for i in range(3):
        print(i)
        Jacobiano1[1][i] = diff(NN[i], eta)

0
1
2
0
1
2


In [4]:
Jacobiano2 = np.array([[0, 0],[2, 0],[0, 1.5]])

In [5]:
jacobianocompleto = np.dot(Jacobiano1, Jacobiano2)
print(jacobianocompleto)

print(np.linalg.inv(jacobianocompleto))


[[ 0.  -1.5]
 [ 2.  -1.5]]
[[-0.5         0.5       ]
 [-0.66666667 -0.        ]]


In [6]:
matrizH = np.array([[1, 0, 0, 0],[0, 0, 0, 1],[0, 1, 1, 0]])
print(matrizH)

[[1 0 0 0]
 [0 0 0 1]
 [0 1 1 0]]


In [8]:
N1 = a0 + a1*x + a2*y
print(N1)
N2 = a3 + a4*x + a5*y
print(N2)
N3 = a6 + a7*x + a8*y
print(N3)
Na = np.array([[1, x, y, 0, 0, 0],[0, 0, 0,1, x, y]])
print(Na)
AA = np.array([[1, x1, y1, 0, 0, 0],[0, 0, 0, 1, x1, y1],[1, x2, y2, 0, 0, 0],[0, 0, 0, 1, x2, y2],[1, x3, y3, 0, 0, 0],[0, 0, 0, 1, x3, y3]])
print(AA)
AAA = np.linalg.inv(AA)
NN = np.dot(Na, AAA)





print(AAA)
print(NN)


a0 + a1*x + a2*y
a3 + a4*x + a5*y
a6 + a7*x + a8*y
[[1 x y 0 0 0]
 [0 0 0 1 x y]]
[[1 x1 y1 0 0 0]
 [0 0 0 1 x1 y1]
 [1 x2 y2 0 0 0]
 [0 0 0 1 x2 y2]
 [1 x3 y3 0 0 0]
 [0 0 0 1 x3 y3]]


TypeError: No loop matching the specified signature and casting was found for ufunc inv